CC=gcc -Wall -Wextra

all: m5c4_fork m5c7_shell m5c8_pipes m5c9_pipes

m5c4_fork: m5c4_fork.c
	$(CC) -o m5c4_fork $^

m5c7_shell: m5c7_shell.c
	$(CC) -o m5c7_shell $^

m5c8_pipes: m5c8_pipes.c
	$(CC) -o m5c8_pipes $^

m5c9_pipes: m5c9_pipes.c
	$(CC) -o m5c9_pipes $^
